kind: Service
apiVersion: v1
metadata:
  name: databasedemo
  labels:
    app: databasedemo
spec:
  type: ClusterIP
  selector:
    app: databasedemo
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: databasedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: databasedemo
  template:
    metadata:
      labels:
        app: databasedemo
        version: v1
    spec:
      containers:
      - name: databasedemo
        image: databasedemo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
