GET http://localhost:8081/userapi/all

###
GET http://localhost:8081/userapi/get/4

###
POST  http://localhost:8081/userapi/add
Content-Type: application/json

{
    "userName":"ramnath"
}
###
PUT  http://localhost:8081/userapi/update/4
Content-Type: application/json

{
    "userName":"vinod"
}

###
DELETE  http://localhost:8081/userapi/delete/5

###
POST http://localhost:8081/taskapi/add/1
Content-Type: application/json

{
    "title":"learn helidon",
    "completed":false    
}

###
GET  http://localhost:8082/taskapi/all