kind: Service
apiVersion: v1
metadata:
  name: firstservice
  labels:
    app: firstservice
spec:
  type: ClusterIP
  selector:
    app: firstservice
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: firstservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstservice
  template:
    metadata:
      labels:
        app: firstservice
        version: v1
    spec:
      containers:
      - name: firstservice
        image: firstservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
